[package]
name = "osu_replay_render"
version = "0.3.2"
edition = "2024"
license = "MIT"

[dependencies]
osu_replay_judge = { git = "https://github.com/Ohdmire/osu-replay-judge.git", branch = "master" }
wgpu = "24"
raw-window-handle = "0.6"
pollster = "0.4"
png = "0.17"
jpeg-decoder = "0.3"
ab_glyph = "0.2"

[profile.release]
lto = "thin"

[lib]
name = "osu_replay_render"
path = "src/lib.rs"

[[bin]]
name = "osu_replay_render"
path = "src/main.rs"
