[package]
name = "osu_replay_render"
version = "0.1.0"
edition = "2024"

[dependencies]
osu_replay_judge = { path = "../osu-replay-judge" }
wgpu = "24"
pollster = "0.4"
png = "0.17"
jpeg-decoder = "0.3"
ab_glyph = "0.2"

[profile.release]
lto = "thin"

[[bin]]
name = "osu_replay_render"
path = "src/main.rs"
